- playground/src/components/Intro.vue
> fix(playground): color in dark mode

- website/guide/introduction.md
Signed-off-by: ssshuai1999 <ssshuai1999@gmail.com>
> Fix typos in introduction

- crates/cli/src/print.rs
Signed-off-by: ssshuai1999 <ssshuai1999@gmail.com>
Thanks for your advice.
> fix(52): normalize file path output in command line

- crates/napi/package.json
- crates/napi/yarn.lock
> Revert "Update dependency @swc-node/register to v1.5.2"

- Cargo.lock
- crates/config/src/rule_config.rs
- crates/core/Cargo.toml
- crates/core/src/pattern.rs
- crates/core/src/ts_parser.rs
> feat: add thiserror to TSParseError and PatternError

- crates/cli/src/verify.rs
- crates/config/src/lib.rs
- crates/config/src/referent_rule.rs
- crates/config/src/relational_rule.rs
- crates/config/src/rule_config.rs
- crates/napi/src/lib.rs
> feat: add support for util rule matches

- Cargo.lock
- crates/cli/src/lsp.rs
- crates/lsp/Cargo.toml
- crates/lsp/src/lib.rs
Part of https://github.com/ast-grep/ast-grep/issues/283
related vscode plugin pr is here https://github.com/ast-grep/ast-grep-vscode/pull/14
> feat: 🎸 basic impl the lsp scan

- xtask/src/main.rs
> chore: add cargo build before git tag

- Cargo.toml
- crates/cli/Cargo.toml
- crates/config/Cargo.toml
- crates/core/Cargo.toml
- crates/dynamic/Cargo.toml
- crates/language/Cargo.toml
- crates/lsp/Cargo.toml
- crates/napi/Cargo.toml
Use workspace package info to reduce maintenance
> chore: use workspace package info to reduce maintenance

- crates/cli/src/print/interactive_print.rs
- crates/cli/src/print/mod.rs
- crates/cli/src/run.rs
- crates/config/src/rule.rs
- crates/config/src/rule_config.rs
- crates/core/src/lib.rs
- crates/core/src/matcher.rs
- crates/core/src/matcher/node_match.rs
- crates/core/src/matcher/pattern.rs
- crates/core/src/meta_var.rs
- crates/core/src/node.rs
- crates/core/src/ops.rs
- crates/core/src/replacer.rs
- crates/core/src/source.rs
- crates/language/src/lib.rs
- crates/language/src/rust.rs
- crates/napi/src/doc.rs
- crates/napi/src/sg_node.rs
> [WIP] fix: use doc in replacer

- Cargo.toml
- benches/Cargo.toml
- crates/cli/Cargo.toml
- crates/config/Cargo.toml
- crates/core/Cargo.toml
- crates/dynamic/Cargo.toml
- crates/language/Cargo.toml
- crates/lsp/Cargo.toml
- crates/napi/Cargo.toml
- xtask/Cargo.toml
> chore: use workspace.deps to manage crates self

- crates/language/src/rust.rs
I've added some tests related to issue #412, along with some tests for the update struct syntax and spread (`..`) . However, the tests involving wildcard pattern (`_`)  are currently failing and have been commented out for the time being.
> wildcard and spread rust tests

- crates/language/src/lib.rs
Ref: https://www.typescriptlang.org/docs/handbook/esm-node.html#new-file-extensions
> feat: supports mts and cts extensions

- crates/core/src/replacer.rs
- crates/core/src/replacer/indent.rs
- crates/core/src/source.rs
- crates/napi/src/doc.rs
> feat: implement indentation sensitive fixer

- crates/cli/src/error.rs
Thanks for the new release! Ran into a little typo.
> fix(cli): suggest correct flag when LanguageNotSpecified

- Cargo.lock
- crates/language/Cargo.toml
- crates/language/src/lib.rs
- crates/language/src/parsers.rs
- crates/language/src/scala.rs
I don't know any rust, but I had a go. 
In particular, I'm not sure what the `mod scala;` in `crates/language/src/lib.rs` is for. So a thorough review is welcome.
Tested on a real project:
> feat: add Scala support

- crates/language/src/lib.rs
- Uses the `FromStr` implementation for deserializing, which allows the aliases to be used when writing a rule YAML file
- Adds the long-form names for some of the languages to the `FromStr` impl
- Normalizes the name to lowercase so that casing doesn't matter (e.g. `tsx` vs. `Tsx` vs. `TSX`)
See also https://github.com/ast-grep/ast-grep.github.io/pull/163
> feat: Use existing language FromStr impl when Deserializing

- crates/cli/src/new.rs
- crates/cli/tests/scan_test.rs
- crates/cli/tests/verify_test.rs
> chore: rename initial test dir to rule-tests

- crates/cli/src/print/cloud_print.rs
- crates/cli/src/print/colored_print.rs
- crates/cli/src/print/interactive_print.rs
- crates/cli/src/print/json_print.rs
- crates/cli/src/run.rs
- crates/core/src/lib.rs
- crates/core/src/node.rs
Part of #464 
This pull request only supports reporting lines around the match. And the display style is not supported yet.
> feat: print context of matched nodes

- crates/cli/src/config.rs
- crates/cli/src/run.rs
- crates/cli/src/scan.rs
fix #546
This pull request adds more detailed explanation and makes value placeholder more descriptive.
> feat: improve readability of argument value

- crates/cli/src/run.rs
- crates/cli/src/scan.rs
- crates/cli/src/utils.rs
> refactor: organize options by clap flatten

- crates/cli/src/error.rs
- crates/cli/src/run.rs
- crates/cli/src/scan.rs
- crates/cli/src/utils.rs
> refactor: reduce code duplication

- crates/cli/src/lib.rs
- crates/cli/src/print/json_print.rs
- crates/cli/src/print/mod.rs
- crates/cli/src/run.rs
- crates/cli/src/scan.rs
- crates/cli/src/utils.rs
> feat: support multiple JSON printing style

- crates/cli/src/config.rs
- crates/cli/src/error.rs
- crates/cli/src/lsp.rs
- crates/cli/src/scan.rs
- crates/cli/src/verify.rs
> feat: add option `scan --rule-id <rule_id>…`

- Cargo.lock
- crates/cli/Cargo.toml
- crates/cli/src/lib.rs
Support for generating shell completions.
Closes: https://github.com/ast-grep/ast-grep/issues/589
I have verified these changes via tested locally.
https://github.com/ast-grep/ast-grep/assets/38807139/ef8b969e-2eb5-4345-932a-be4093466a48
> feat(cli): add shell completions feature and related test

- crates/cli/src/completions.rs
> fix(cli): update typos and usage instructions

- crates/cli/src/print/json_print.rs
fix https://github.com/ast-grep/ast-grep/issues/635
> feat: adds `note` field for json output

- crates/pyo3/pyproject.toml
> chore: complete some project metadata in `pyproject.toml`

- README.md
Just adding the link to the MacPorts homepage
> docs: add MacPorts URL

- README.md
Something I noticed while reading the README.
Personally I would suggest to use the terminology of DSL (domain specific language) instead of 'the pattern' however that seems a bigger change.
> change: nitpick english language

- .github/workflows/napi.yml
- crates/napi/npm/linux-arm64-gnu/README.md
- crates/napi/npm/linux-arm64-gnu/package.json
- crates/napi/package.json
I do think this require sponsorship :/
> feat: add support for arm64 linux napi

- crates/core/src/replacer/indent.rs
- crates/napi/src/doc.rs
> feat: applyRewriters

- crates/config/src/rule/deserialize_env.rs
- crates/config/src/rule_config.rs
- crates/config/src/rule_core.rs
- crates/core/src/replacer/template.rs
- crates/napi/src/doc.rs
- crates/pyo3/src/py_node.rs
this paves way to RuleCore without lang
> refactor: use DeserializeEnv to get RuleCore

- Cargo.lock
- crates/pyo3/Cargo.toml
> Revert "fix(deps): update rust crate pyo3 to 0.20.3"

- crates/config/src/transform/mod.rs
- crates/config/src/transform/rewrite.rs
> feat: export used meta-var in transform

- crates/cli/src/run.rs
- crates/config/src/rule/mod.rs
- crates/core/src/match_tree/match_node.rs
- crates/core/src/match_tree/strictness.rs
- crates/pyo3/ast_grep_py/__init__.py
- crates/pyo3/tests/test_rule.py
> feat: add strictness in PyO3

- .github/workflows/napi.yml
- crates/napi/npm/linux-arm64-musl/README.md
- crates/napi/npm/linux-arm64-musl/package.json
fix https://github.com/ast-grep/ast-grep/issues/1227
> feat: support arm64 musl 

- crates/cli/src/scan.rs
- crates/cli/src/utils/rule_overwrite.rs
> feat: support override severity of unused-suppression
