ast-grep/ast-grep

crates/cli/src/languages/csharp.rs
crates/cli/src/languages/mod.rs
crates/cli/src/languages/python.rs

Thanks for the useful tool, but currently `--lang=py` doesn't work. \_(:з」∠)\_
Since `$` is not a valid identifier in Python (https://docs.python.org/3/reference/lexical_analysis.html#identifiers), I have re-implemented the language `Python` with reference to the csharp implementation (9a14a4b71cc348274ad6d153fc9011aedf9b490e). (・ω< )★

[fix] reimplement language `Python` to override `expando_char`

---

README.md
website/.vitepress/config.ts
website/guide/introduction.md
website/index.md

[docs] fix a small typo (`ligthning` -> `lightning`)

---

Cargo.lock
crates/cli/src/scan.rs
crates/config/Cargo.toml
crates/config/src/rule.rs
crates/config/src/rule_collection.rs

Starting this PR because I want to only apply rules to certain files in my codebase.
"Contingent rules" seem to be the rules which are only applied to certain files. [4548c6f](https://github.com/ast-grep/ast-grep/pull/82/commits/4548c6f37a5ee51e62f4714513fbddefdcdaccd2) adds loading for these rules, adds a `matches_path` function to `RuleConfig` which can be used to see if a rule should be run on a given path, and adds a test for testing both of these.
Note: Globset was used because this was the same library that `ignore` uses. The `Glob` object can be used to build [overrides](https://docs.rs/ignore/latest/ignore/overrides/struct.Glob.html) for ignore's WalkBuilder. When we separate the rules into TenuredRules and ContingentRules, we will be able to efficiently build walk builders for …

feat: add contingent rules with tests

---

crates/config/src/relational_rule/mod.rs
crates/config/src/relational_rule/stop_by.rs
crates/core/src/node.rs

We can skip creating a tree-cursor if we just want to match one node around. Creating a tree-cursor is quite expensive.
`stop_by`'s `find` now gets three arguments: `once`, `multi` and `finder`. All of the three are closures. We create iterator and, thusly, cursor only when `stop_by` is `end`.
Before:
```sh
hyperfine -i 'sg scan -c ../eslint/sgconfig.yml src > /dev/null'
Benchmark 1: sg scan -c ../eslint/sgconfig.yml src > /dev/null
Time (mean ± σ):      3.310 s ±  0.055 s    [User: 9.473 s, System: 0.128 s]
Range (min … max):    3.235 s …  3.405 s    10 runs
Warning: Ignoring non-zero exit code.
```
After:
```shell
hyperfine -i 'sg scan -c ../eslint/sgconfig.yml src > /dev/null'
Benchmark 1: sg scan -c ../eslint/sgconfig.yml src > /dev/null
Time (mean ± σ):      2.990 s ±  0.069 s …
```

perf: optimize relational rule's stopBy: neighbor

---

crates/cli/src/run.rs

Added shorthand for `--accept-all`: `sg run -A -p 'ast_query' --rewrite 'rewrite_query' -l rs`
fix #386

added `-A` alias to `run --accept-all`

---

crates/cli/src/error.rs
crates/cli/src/utils.rs

Preparation of #156
This style seems not supported by `termcolor` (considering Windows support), so I guess it's better to replace it before the refactor.
Style change: dotted underline -> underline

refactor: add comments for ansi link

---

crates/core/src/match_tree.rs
crates/core/src/node.rs
crates/core/src/replacer.rs
crates/core/src/source.rs
crates/napi/__test__/index.spec.ts
crates/napi/src/doc.rs

We used to expose underlying binary array of the Source. However, in JavaScript.
The start_pos is in byte offset.  But underlying binary array can be in u16.
This pull request changes the interface of source by replacing as_slice with get_range.
So source can handle this discrepancy gracefully.
fix #400
Also added test cases.

    fix: use get_range instead as_slice to handle byte_offset and underlying arry size

---

crates/core/src/lib.rs
crates/core/src/match_tree.rs

See #374 .
We can skip non-matching trivial nodes in source to make the matching more AST-like.

feat: use smarter matching algorithm

---

crates/cli/Cargo.toml

This should put the `LICENSE` file itself in the [crate upload](https://crates.io/crates/ast-grep). Downstream distributors who need to include the license along with the software can then build from the crate tarball.

Include license file in the primary crate

---

crates/cli/src/print/colored_print.rs
crates/cli/src/print/colored_print/test.rs
crates/cli/src/run.rs
crates/core/src/node.rs

fix #464 
I'm pretty happy the `DisplayContext` and `MatchMerger` can gracefully be extended to support contextual printing.
`sg -p 'Some($A)' -B 1 -A 2`

feat: add before/after context

---

schemas/project.json

For `sgconfig.yml`, related: https://github.com/ast-grep/ast-grep-vscode/issues/31
Not quite sure where it should be placed, temporarily at `schema/` folder

chore: add project json schema for intellisense

---

crates/cli/src/config.rs
crates/cli/src/error.rs
crates/cli/src/verify.rs

When done, this should close #248 and I will be submitting a PR on https://github.com/ast-grep/ast-grep.github.io to update the docs. During dev/testing, I had some issues around snapshots, I fixed one of them and will just mention the other in case that’s unexpected behaviour. Ofc let me know if I broke anything.
Implemented by adding a glob filter on the test directory walker. The glob filter is not applied to the snapshots directory nested inside of it. This does mean the whole snapshots dir is always loaded regardless of the glob filter’s value, let me know if that’s an issue.
The snapshot dir (be it from CLI arg or test config) is taken into account when determining where to load snapshots from but was ignored when determining the directory to save snapshots to (always using …

feat(test): add test case filter for sg test

---

crates/config/src/lib.rs
crates/config/src/string_conversion.rs
crates/config/src/transform.rs

This implements the three string transformations described in #436:
> **Transform**
> Similar to https://www.typescriptlang.org/docs/handbook/2/template-literal-types.html#intrinsic-string-manipulation-types
>
> ```yaml
> NEW_VAR: 
>   transform: [uppercase, lowercase, capitalize]
>   source: $VAR
> ```
(with the keyword `convert` as discussed in the comments/review)
Here's my actual use-case (slightly anonymized):
```yaml
id: foo
language: python
rule:
pattern: ObjectStatus.$A
regex: ObjectStatus.(.*)_statuses
transform:
B:
replace:
source: $A
replace: '(.*)_statuses'
by: '${1}_STATUSES'
CHANGED:
convert:
source: $B
convert: uppercase
fix:
$CHANGED
```
This turns `ObjectStatus.foo_statuses` to `FOO_OBJECT_STATUSES` everywhere.

Implement string conversions

---

crates/config/src/string_conversion.rs
crates/config/src/transform.rs

These conversions can be tedious to write out as regexps (not to mention they were fun to implement).
```yaml
convert:
identifier:
from: snakecase
to: camelcase
```
converts e.g. `snakes_live_in_forests` to `snakesLiveInTheForests`.
```yaml
convert:
identifier:
from: camelcase
to: snakecase
letterCase: capitalize
```
converts e.g. `snakesLiveInTheForests` to `Snakes_Live_In_The_Forests` (which is pretty outré, but then again hungarian notation is a thing too...).

Add identifier convention conversions

---

.github/workflows/pyo3.yml
.github/workflows/pypi.yml
crates/pyo3/ast_grep_pyo3/__init__.py
crates/pyo3/ast_grep_pyo3/ast_grep_pyo3.pyi
crates/pyo3/pyproject.toml

- import `Unpack` from `typing_extensions` to support Python 3.8. (3.8 is the lowest aliving version[^1].)
- Use [PEP 563](https://peps.python.org/pep-0563/) in `.py` file to support `|` in type annotations. We don't need to explicitly use PEP 563 in `.pyi` because it is always enabled in stubs[^2].
This PR might be helpful for https://twitter.com/hd_nvim/status/1721013482286629077
[^1]: [Status of Python versions](https://devguide.python.org/versions/)
[^2]: [Type Stubs - Syntax](https://typing.readthedocs.io/en/latest/source/stubs.html#syntax)

chore: support Python 3.8 by using `typing-extensions`

---

crates/cli/src/run.rs

Avoid panic when run `sg` without providing any cli args.

fix: out of bounds panic

---

README.md

Add a line in the installation section touching on how to install `ast-grep` via [MacPorts](https://macports.org)
Ports page for `ast-grep`: https://ports.macports.org/port/ast-grep/

doc: add MacPorts install info

---

crates/cli/src/run.rs
crates/cli/src/utils.rs
crates/config/src/rule/mod.rs
crates/config/src/transform/mod.rs
crates/core/src/match_tree.rs
crates/core/src/matcher/pattern.rs
crates/core/src/meta_var.rs
crates/core/src/node.rs
crates/core/src/ops.rs
crates/core/src/replacer.rs
crates/core/src/replacer/structural.rs
crates/core/src/replacer/template.rs
crates/language/src/lib.rs
crates/language/src/rust.rs
crates/napi/src/sg_node.rs

This pull request revamps `Pattern` implementation. Pattern was backed by tree-sitter Root and now it is backed by a custom data-structure.
* reduce pattern Root traversal during search
* better cloning
* less dependent on tree-sitter
* more intuitive meta variable
* more flexible pattern code normalization

feature: revamp pattern implementation

---

crates/cli/src/run.rs
crates/cli/src/scan.rs
crates/cli/src/utils.rs

Refactor to unify the handling of file path discovery and standard input processing by abstracting workers into two sub-traits: 
* PathWorker 
* StdInWorker
each with new run methods; modified run_worker function to accept a PathWorker trait reference.

refactor: unify run_worker and run_std_in

---

crates/config/src/fixer.rs
crates/config/src/rule_config.rs
crates/config/src/rule_core.rs
crates/core/src/replacer.rs
crates/core/src/replacer/indent.rs
crates/core/src/replacer/template.rs

fix #868
BREAKING CHANGE: IndentSensitive is not used anymore. Just change it to Source. Source is reexported in replacer mod so you can mechanically change IndentSensitive to Source.

refactor: remove IndentSensitive trait

---

Cargo.lock
Cargo.toml
crates/config/Cargo.toml
crates/core/Cargo.toml
crates/dynamic/Cargo.toml
crates/language/Cargo.toml
crates/napi/Cargo.toml

chore: bump tree-sitter version

---

Cargo.lock
crates/language/Cargo.toml
crates/language/src/haskell.rs
crates/language/src/lib.rs
crates/language/src/parsers.rs

This adds support for Haskell by integrating [`tree-sitter-haskell`](https://github.com/tree-sitter/tree-sitter-haskell). While it compiles, even rudimentary patterns such as `return $A` or `$A $B` do not work yet (probably an upstream issue?), therefore I will mark this PR as a draft for now.

feat(language): Add support for Haskell via `tree-sitter-haskell`

---

.github/workflows/release.yml

Release workflow failed. https://github.com/ast-grep/ast-grep/actions/runs/9050071514/job/24865070006
https://github.com/ast-grep/ast-grep/actions/runs/9050071514/job/24865070006
```
Run files=(aarch64-apple-darwin x86_64-apple-darwin x86_64-unknown-linux-gnu aarch64-unknown-linux-gnu)
unzip:  cannot find or open artifacts/sg-aarch64-apple-darwin.zip, artifacts/sg-aarch64-apple-darwin.zip.zip or artifacts/sg-aarch64-apple-darwin.zip.ZIP.
Error: Process completed with exit code 9.
```
This pull request fixes the failure.
Assets `sg-*` were renamed to `app-*` 3a6e55317a7904285b4f0df16c7f1f603a608543, so we need to fix the release workflow.
https://github.com/ast-grep/ast-grep/releases/tag/0.22.2

ci: fix the failure of the release workflow

---

Cargo.lock
crates/lsp/Cargo.toml

napi does not support this
Reverts ast-grep/ast-grep#2066

Revert "fix(deps): update rust crate tower-lsp-server to 0.22.0"
